### ISSUE TITLE
同类型存储多VG支持

### ISSUE THREAD

**Issue by zwForrest** [carina-io/carina#10]
目前同类型的存储都会自动创建一个vg，因此后续都将会使用这个vg创建lv。而有些时候针对隔离要求较高的业务可能需要独占盘，或者其他原因需要将裸盘划分成多个vg。这样可能是不是支持用户配置vg数量以及对应的磁盘的信息比较合适呢？

**Comment by ZhangZhenhua** [comment]
是的，基于业务独占式的使用某些盘。

carina后续会开放路线图，也会将这个Issue放进去。
