### ISSUE TITLE
支持磁盘缩容吗

### ISSUE THREAD

**Issue by yeeeee7** [carina-io/carina#193]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by antmoveh** [comment]
不支持，目前存储产品基本都不支持缩容。
这个存储是thin模式，就是随着数据写入盘逐渐变大到限制值

**Comment by yeeeee7** [comment]
thin模式是默认开启的吗
