### ISSUE TITLE
LV not found and Mount.Setup failed

### ISSUE THREAD

**Issue by mtt0** [carina-io/carina#213]
**What happened**:
- lvs 命令的结果里没有 Bound PV（部分）对应的 LV
- Pod 重启后无法挂载存储卷

**What you expected to happen**:
- 正常挂载

**How to reproduce it**:

**Anything else we need to know?**:

- Carina 的版本是 `v0.10.0`, 哈希 `610acdc6e711dee86aa660fb4c111f7d94044c16`。从来没升级过...非常抱歉还在问老版本的问题
- 存储类是 Retain 的，今天删除了一些 Released 的 PV，但**没有删除** Bound PV 的 LV（后面发现有些 PV 的 LV 原先就不存在）:
> 我非常确定没有删除 Bound PV 的 LV，因为删掉 LV 时的命令行输出我后面拷贝了下，搜索了几个 Bound PV 的 LV，发现并没有出现在被删掉的输出里

```sh
# 先删掉了 volume--pvc
./lvs列出并排除已存在PV的LV.sh | grep volume | awk '{print $1}' | xargs -I{} lvremove /dev/carina-vg-hdd/{}
# 然后删掉了 thin pool 的 lv
./lvs列出并排除已存在PV的LV.sh | awk '{print $1}' | xargs -I{} lvremove /dev/carina-vg-hdd/{}
```

- 集群上有 PVC 和 PV，根据 PV 的 carina.storage.io/path 可以查到对应主机 /dev/carina-vg-hdd 下存在这个卷，/dev/mapper/ 下也有确实有对应的块设备和 thin pool
<img width="1745" alt="image" src="https://github.com/user-attachments/assets/6532b665-4a99-46fd-b54b-3325d416dc15">
<img width="1735" alt="image" src="https://github.com/user-attachments/assets/15b53dd3-087e-42e1-8a70-ededa3530641">

- `kubectl get lv` 有对应的 LogicVolume
<img width="1731" alt="image" src="https://github.com/user-attachments/assets/adeeb2fd-0123-405c-bfcc-032255d8a386">

- 我可以手动创建对应 Pod 的 `.../pvc-xxx/mount` 路径然后通过 `mount` 命令挂载这个卷。但 k8s 上不行，Attach 成功，有对应的 VolumeAttachment，但之后 MountVolume.Setup 报错 404

Attach 成功，存在 VolumeAttachment
<img width="1624" alt="image" src="https://github.com/user-attachments/assets/dfbe0e5d-2b44-4e42-add2-642978baf732">

手动 `mkdir -p  前略/pvc-xxxx/mount` 然后 `mount  /dev/carina-vg-hdd/volume-pvc-xxx`。原先 Attach 成功后 `前略/pvc-xxxx/` 目录并不存在
<img width="1734" alt="image" src="https://github.com/user-attachments/assets/15f75b4c-b56b-4e94-a269-649b39dedffb">

之后 `vol_data.json` 也有了
<img width="1726" alt="image" src="https://github.com/user-attachments/assets/b641d417-2139-4621-94f4-0795bdbae247">

无论是否进行手动挂载，最后都是 MountVolume.Setup 报错 404
<img width="1646" alt="image" src="https://github.com/user-attachments/assets/690152ae-d89d-4585-ac07-56c5e2b74d60">

<img width="1618" alt="image" src="https://github.com/user-attachments/assets/5f6a2142-38b8-42dd-808e-c5ad3074f7ab">

- lvs 命令的结果里没有 Bound PV（部分）对应的 LV

- 今天新创建的 PVC 产生的 PV 有对应的 k8s LogicVolume，`lvs` 输出没有对应的 lv，但它成功地被自动挂载，Pod 正常运行了......和其他一些没有对应 lv 的卷一样
<img width="1663" alt="image" src="https://github.com/user-attachments/assets/bb39ecb1-e7bb-4940-ab07-b0a36816028e">

- PV yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: carina.storage.io
  creationTimestamp: "2024-05-14T16:25:57Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-15a08073-c481-40fe-8931-f9b33b8cff22
  resourceVersion: "258566655"
  uid: 2d281ac9-fee0-4798-a7de-4413992987ef
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data
    namespace: masked
    resourceVersion: "258566639"
    uid: 15a08073-c481-40fe-8931-f9b33b8cff22
  csi:
    driver: carina.storage.io
    fsType: ext4
    volumeAttributes:
      carina.storage.io/disk-group-name: carina-vg-hdd
      carina.storage.io/major: "253"
      # 不同 PV 的 DeviceMinor 不一样，这个是否有影响？ 
      carina.storage.io/minor: "150"
      carina.storage.io/node: k8s02
      carina.storage.io/path: /dev/carina-vg-hdd/volume-pvc-15a08073-c481-40fe-8931-f9b33b8cff22
      csi.storage.k8s.io/pv/name: pvc-15a08073-c481-40fe-8931-f9b33b8cff22
      csi.storage.k8s.io/pvc/name: redis-data
      csi.storage.k8s.io/pvc/namespace: masked
      storage.kubernetes.io/csiProvisionerIdentity: 1715701876853-8081-carina.storage.io
    volumeHandle: volume-pvc-15a08073-c481-40fe-8931-f9b33b8cff22
  mountOptions:
  - rw
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.carina.storage.io/node
          operator: In
          values:
          - k8s02
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-carina-lvm
  volumeMode: Filesystem
status:
  phase: Bound
```

**Environment**:
- CSI Driver version: `antmoveh/csi-node-driver-registrar:v2.1.0`
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```
- Kernel (e.g. `uname -a`): `Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `kubectl`
- Others:

**Main concerns**:
Q1: 请问可能会是什么问题？是否与 https://github.com/carina-io/carina/pull/144 有关？我看这个提交是在 `610acdc6e711dee86aa660fb4c111f7d94044c16` 之后的
Q2: 假如主机重启的话，现在 /dev/carina-vg-hdd 和 /dev/mapper/ 下的这些没有对应 LV 的块设备都会消失？
**Q3: 是否需要/有办法在不丢失数据的情况下重建 LV？感觉可能最好趁现在还挂载着，将重要的数据拷贝出来？**
Q4: 升级是否能解决？

多谢～～～

**Comment by mtt0** [comment]
不太确定那些挂载了没有对应 Linux LV 的 Pod 重启后会怎么样，是否也会无法挂载。因为做了删除悬空 lv 的操作，在没备份的情况下，现在不太敢创建新的 PVC 去测试，怕可能会覆写硬盘里的数据。暂时也不能重启其他 Pod....在备份数据了...

**Comment by antmoveh** [comment]
1. 你这些lvs命令是在主机上执行的还是在csi-carina容器内执行的？ 在容器内才能看到，主机上看不到lvs的数据这是由于lvm缓存导致的
2. 如果重启了服务器，有的服务器存在lvm服务器没有自动启动的情况这需要手动启动lvmd服务
3. 不同pv对应的设备 版本号是不一样的
4. 在k8s中的lv如果不删除的话 carina不会去删除节点上的lv， 你也可以考虑备份一下lv里的数据。
5. not found 这种需要看具体的环境了，很难靠几个图就看出是啥情况
6. 也曾遇到过节点的nfs mount点损坏导致carina的挂载失败

**Comment by mtt0** [comment]
> 1. 你这些lvs命令是在主机上执行的还是在csi-carina容器内执行的？ 在容器内才能看到，主机上看不到lvs的数据这是由于lvm缓存导致的
> 2. 如果重启了服务器，有的服务器存在lvm服务器没有自动启动的情况这需要手动启动lvmd服务
> 3. 不同pv对应的设备 版本号是不一样的
> 4. 在k8s中的lv如果不删除的话 carina不会去删除节点上的lv， 你也可以考虑备份一下lv里的数据。
> 5. not found 这种需要看具体的环境了，很难靠几个图就看出是啥情况
> 6. 也曾遇到过节点的nfs mount点损坏导致carina的挂载失败

非常感谢~!

1. 在 csi-carina-node 容器里的结果 与 在相同主机上的结果一致

<img width="1403" alt="image" src="https://github.com/user-attachments/assets/b52a2f65-544a-486d-9d39-4ef721f01d57">
<img width="1665" alt="image" src="https://github.com/user-attachments/assets/a8d9cedd-edae-4907-92fd-2f7c76a173a1">

2. 因为 1 两者结果一致，在 lvmd 正常自启的情况下，有没有可能重启后现在挂正常挂载（但找不到对应 LV）的 /dev/mapper/carina--vg--hdd--xxxx 会消失

4. 嗯，要备份的，就怕万一

6. 主机上没有挂其他 NFS 文件系统，也不作为 NFS 服务器，看了下 https://github.com/carina-io/carina/pull/202 似乎不是这个原因

**Comment by antmoveh** [comment]
1 会在/dev/carina目录下创建个设备用于挂载， 并不在/dev/mapper下。
2 看看/dev/carina下那个设备是在kubelet调用csi的时候，创建出的设备
3. 你可以尝试先缩容Pod， 然后看看对应节点上的/dev/carina目录下的设备，如果有和lv同名的可以先删了
4. 或者你手动 mknod 根据lv卷的 设备号创建出个设备

**Comment by mtt0** [comment]
> 1 会在/dev/carina目录下创建个设备用于挂载， 并不在/dev/mapper下。 2 看看/dev/carina下那个设备是在kubelet调用csi的时候，创建出的设备 3. 你可以尝试先缩容Pod， 然后看看对应节点上的/dev/carina目录下的设备，如果有和lv同名的可以先删了 4. 或者你手动 mknod 根据lv卷的设备号（pv的major 那俩号） 在/dev/carina下创建出个设备

手动 mknod 创建设备有效，创建后就能自动挂载上了，pod 正常启动。多谢～

**Comment by antmoveh** [comment]
1. 我现在不确定你的问题是否修复
2. 还有一个办法是将 k8s中那个lv，导出一份yaml，然后将yaml中的status删除
3. 然后再执行`kubectl delete -f lv.yaml` && `kubectl apply -f lv.yaml` 触发lv的重新更新逻辑
4. 这个操作要快点，因为有个每隔十分钟的巡检，检查到没有lv的话会删除宿主机上的lv卷

**Comment by mtt0** [comment]
感谢感谢～～

找到大概的问题原因了，之前服务器从另一个环境迁移过来的，第三方用的类似虚拟机克隆（全盘拷贝）的方法（具体技术我不太了解）迁移过来的。自从迁移过来后，所有新建卷都没有底层的 LV（我一一比对过了，有 LV 的全是迁移前创建的）。Carina Controller 的日志了没找到 error，只看到 info，所以大概率是迁移造成的

```sh
$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

$ lvm version
# Output
  LVM version:     2.02.180(2)-RHEL7 (2018-07-20)
  Library version: 1.02.149-RHEL7 (2018-07-20)
  Driver version:  4.37.1
  Configuration:   ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=
/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --li
bexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-default-dm-run-dir=/run -
-with-default-run-dir=/run/lvm --with-default-pid-dir=/run --with-default-locking-dir=/run/lock/lvm --with-usrlibdir=/usr/lib64 --enable-lvm1_fallback 
--enable-fsadm --with-pool=internal --enable-write_install --with-user= --with-group= --with-device-uid=0 --with-device-gid=6 --with-device-mode=0660 -
-enable-pkgconfig --enable-applib --enable-cmdlib --enable-dmeventd --enable-blkid_wiping --enable-python2-bindings --with-cluster=internal --with-clvm
d=corosync --enable-cmirrord --with-udevdir=/usr/lib/udev/rules.d --enable-udev_sync --with-thin=internal --enable-lvmetad --with-cache=internal --enab
le-lvmpolld --enable-lvmlockd-dlm --enable-lvmlockd-sanlock --enable-dmfilemapd
```


- to 1. 未修复
- 2~5 我会尝试一下，如果我 pod 缩容，然后把 deploy `csi-carina-provisioner`（包含 `csi-carina-controller` Pod）停了，csi-daemonset `carina-node` 留着，是不是就能非常安全地 `kubectl delete -f lv.yaml && kubectl apply -f lv.yaml`，而不用担心 lv 被删除，并且正常挂载的那些在操作期间也不会受到影响（已经 attach 过了，`csi-carina-provisioner` 里的 `csi-carina-attacher` 不运行应该也没事吧）？

**Comment by mtt0** [comment]
对一个 LV，试了下 2～5：

csi-carina-node 里确实有了：
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/bcbd11c4-6cec-457b-b5d0-acd83231ceda">
主机上没有，因为 lvm 缓存的原因吗？如果 csi-carina-node 的对应节点重启了，是不是之后 csi-carina-node 里也会没有了（就造成现在这种情况）：
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/7e8309df-c25a-4e3b-b816-7c794cdd3488">

**Comment by antmoveh** [comment]
清理是csi-carina-node做的

**Comment by antmoveh** [comment]
不会 会一直存在 主机看不见是缓存原因
