### ISSUE TITLE
deploy problem

### ISSUE THREAD

**Issue by yuexian1234** [carina-io/carina#25]
**What happened**:
when use gen_webhookca.sh,have  error
**What you expected to happen**:
no err

**How to reproduce it**:
kubectl create secret generic ${secret} \
        --from-file=tls.key="${tmpdir}"/server-key.pem \
        --from-file=tls.crt="${tmpdir}"/server-cert.pem \
        --dry-run=true -o yaml |
    kubectl -n ${namespace} apply -f -
fix --dry-run=client to --dry-run=true
**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhangkai8048** [comment]
yes，we think so ,this will be add in version 0.9.1

**Comment by antmoveh** [comment]
The problem no longer exists
