### ISSUE TITLE
IO限流方面的问题

### ISSUE THREAD

**Issue by TheBeatles1994** [carina-io/carina#28]
我看到 io-throttling 相关代码并没有设置 /sys/fs/cgroup/blkio/tasks 文件，我在 cgroupv1 上测试了下必须要设置该文件后才能进行 directIO限流，当时项目不设置该文件的考虑是什么呢？

https://github.com/carina-io/carina/blob/185cf9bc7e7b7299270df1370fb9190e5a2585d3/controllers/pod_controller.go#L38-L46

**Comment by antmoveh** [comment]
很抱歉 刚注意到这个问题， 等我测试一下看看是不是个问题

**Comment by antmoveh** [comment]
你好 我策略一下是可以限速的。因为我们将限速配置在了/sys/fs/cgroup/blkio根目录，而不类似docker的在里边创建个目录，所以我们这个不需要设置task; 你如果查看/sys/fs/cgroup/blkio/cgroup.procs文件的能看到所有的PID
```
[root@carina-block-pod /]# dd if=/dev/xvda of=/dev/null bs=1M
228+0 records in
227+0 records out
238026752 bytes (238 MB, 227 MiB) copied, 22.6119 s, 10.5 MB/s
```

**Comment by TheBeatles1994** [comment]
明白了，多谢
