### ISSUE TITLE
http://www.opencarina.io/ 挂了

### ISSUE THREAD

**Issue by lxd5866** [carina-io/carina#47]
**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by antmoveh** [comment]
ok  sorry

**Comment by antmoveh** [comment]
服务器在国外，忒翻墙才能访问图片。
