### ISSUE TITLE
咋们那个故障转移的功能非常不错，但是存在一些问题

### ISSUE THREAD

**Issue by fanhaouu** [carina-io/carina#77]
咋们目前的逻辑是先强制删除POD，然后再删除PVC，这个逻辑有俩个潜在问题。

第一个问题：删除POD后，由于工作负载的作用，会立马创建新的POD，而这个新的POD会进入调度流程。
假如此时PVC还没有被删除，由于PV亲和性约束，那么该POD就会处于Pending状态，而且由于pvc为POD所用，此时是无法成功删除PVC的，迁移功能失效。因此，应该避免POD受之前PVC影响。

第二个问题：删除PVC后，就不停尝试新建PVC，没有考虑类似statefulset 中PVC Template的场景（删除POD后，对应的工作负载会自动创建PVC）。因此，新建PVC之前，应该先查询一下是否存在状态正常的PVC。

针对第一个问题，有俩种改进策略：
一、先patch PVC，去除掉pvc protection的finallizer，然后再删除PVC，然后再创建新的PVC；
二、先删除PVC，然后再删除POD，之后PVC会被清理回收，最后再创建新的PVC；

针对第二个问题，新建PVC之前，应该先查询一下是否存在状态正常的PVC。

**Comment by fanhaouu** [comment]
可以一起讨论下，确认有问题的话，我愿意重构这块逻辑。

**Comment by antmoveh** [comment]
关于第一个问题 这个确实产生PVC无法删除的问题吗？ 我理解的是POD与PVC Bound才会导致PVC无法删除。 而Pod Pending状态是可以删除PVC的

**Comment by antmoveh** [comment]
关于第二个问题 我决定可以做这方面的优化， 但是要检查PVC的状态以及创建时间等，避免是上次删除失败的。

**Comment by fanhaouu** [comment]
> 关于第一个问题 这个确实产生PVC无法删除的问题吗？ 我理解的是POD与PVC Bound才会导致PVC无法删除。 而Pod Pending状态是可以删除PVC的

你的理解是对的，我的记忆有偏差，在pvc_protection_controller.go中，我没注意到有个pod.Spec.NodeName == ""的逻辑判断，之前以为仅仅是看pod的PVC Claim

**Comment by zhangkai8048** [comment]
是的，这里确实是存在问题，很感谢你的意见
