### ISSUE TITLE
nodestorageresource's status is inconsistent with vg/disk situation

### ISSUE THREAD

**Issue by fanhaouu** [carina-io/carina#87]
**What happened**:
nodestorageresource's status is inconsistent with vg/disk situation

**What you expected to happen**:
nodestorageresource's status should be consistent with vg/disk situation

**How to reproduce it**:
1、for configmap，add new device loop5-7

    {
      "diskSelector": [
        {
          "name": "carina-vg-ssd" ,
          "re": ["/dev/vdb","/dev/vdd","loop0+","loop1+","loop3+","loop4+","loop5+","loop6+"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
        {
          "name": "carina-raw" ,
          "re": ["/dev/vdc","loop2+","loop7+"],
          "policy": "RAW",
          "nodeLabel": "kubernetes.io/hostname"
        }
      ],
      "diskScanInterval": "300",
      "schedulerStrategy": "spreadout"
    }

2、waiting about two minutes, then add new device loop5~7
[root@iZrj97dgwrb4i319c5ec0lZ opt]# lsblk
NAME                                                                          MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
vda                                                                           253:0    0  40G  0 disk 
└─vda1                                                                        253:1    0  40G  0 part /
vdb                                                                           253:16   0  10G  0 disk 
├─carina--vg--ssd-thin--pvc--36c6a41d--9712--45a6--9a0d--329bd576beb1_tdata   252:1    0   3G  0 lvm  
│ └─carina--vg--ssd-thin--pvc--36c6a41d--9712--45a6--9a0d--329bd576beb1-tpool 252:2    0   3G  0 lvm  
│   ├─carina--vg--ssd-thin--pvc--36c6a41d--9712--45a6--9a0d--329bd576beb1     252:3    0   3G  1 lvm  
│   └─carina--vg--ssd-volume--pvc--36c6a41d--9712--45a6--9a0d--329bd576beb1   252:4    0   3G  0 lvm  /var/lib/kubelet/pods/8de7eb1a-53e3-
└─carina--vg--ssd-thin--pvc--17888c0f--5a11--4384--b97d--b54d46cf4b51_tdata   252:6    0   3G  0 lvm  
  └─carina--vg--ssd-thin--pvc--17888c0f--5a11--4384--b97d--b54d46cf4b51-tpool 252:7    0   3G  0 lvm  
    ├─carina--vg--ssd-thin--pvc--17888c0f--5a11--4384--b97d--b54d46cf4b51     252:8    0   3G  1 lvm  
    └─carina--vg--ssd-volume--pvc--17888c0f--5a11--4384--b97d--b54d46cf4b51   252:9    0   3G  0 lvm  /var/lib/kubelet/pods/cfb07e2b-be66-
vdc                                                                           253:32   0  11G  0 disk 
└─vdc2                                                                        253:34   0   5G  0 part 
vdd                                                                           253:48   0  11G  0 disk 
loop0                                                                           7:0    0   5G  0 loop 
loop1                                                                           7:1    0  15G  0 loop 
├─carina--vg--ssd-thin--pvc--36c6a41d--9712--45a6--9a0d--329bd576beb1_tmeta   252:0    0   4M  0 lvm  
│ └─carina--vg--ssd-thin--pvc--36c6a41d--9712--45a6--9a0d--329bd576beb1-tpool 252:2    0   3G  0 lvm  
│   ├─carina--vg--ssd-thin--pvc--36c6a41d--9712--45a6--9a0d--329bd576beb1     252:3    0   3G  1 lvm  
│   └─carina--vg--ssd-volume--pvc--36c6a41d--9712--45a6--9a0d--329bd576beb1   252:4    0   3G  0 lvm  /var/lib/kubelet/pods/8de7eb1a-53e3-
└─carina--vg--ssd-thin--pvc--17888c0f--5a11--4384--b97d--b54d46cf4b51_tmeta   252:5    0   4M  0 lvm  
  └─carina--vg--ssd-thin--pvc--17888c0f--5a11--4384--b97d--b54d46cf4b51-tpool 252:7    0   3G  0 lvm  
    ├─carina--vg--ssd-thin--pvc--17888c0f--5a11--4384--b97d--b54d46cf4b51     252:8    0   3G  1 lvm  
    └─carina--vg--ssd-volume--pvc--17888c0f--5a11--4384--b97d--b54d46cf4b51   252:9    0   3G  0 lvm  /var/lib/kubelet/pods/cfb07e2b-be66-
loop2                                                                           7:2    0  15G  0 loop 
loop3                                                                           7:3    0  15G  0 loop 
loop4                                                                           7:4    0  15G  0 loop 
loop5                                                                           7:5    0  15G  0 loop 
loop6                                                                           7:6    0  15G  0 loop 
loop7                                                                           7:7    0  15G  0 loop 

3、wait, exec vgs and pvs, devicemanager works fine
[root@iZrj97dgwrb4i319c5ec0lZ opt]# vgs
  VG            #PV #LV #SN Attr   VSize  VFree 
  carina-vg-ssd   7   4   0 wz--n- 95.97g 89.96g

[root@iZrj97dgwrb4i319c5ec0lZ opt]# pvs
  PV         VG            Fmt  Attr PSize   PFree  
  /dev/loop1 carina-vg-ssd lvm2 a--  <15.00g <14.99g
  /dev/loop3 carina-vg-ssd lvm2 a--  <15.00g <15.00g
  /dev/loop4 carina-vg-ssd lvm2 a--  <15.00g <15.00g
  /dev/loop5 carina-vg-ssd lvm2 a--  <15.00g <15.00g
  /dev/loop6 carina-vg-ssd lvm2 a--  <15.00g <15.00g
  /dev/vdb   carina-vg-ssd lvm2 a--  <10.00g   3.99g
  /dev/vdd   carina-vg-ssd lvm2 a--  <11.00g <11.00g

4、nodestorageresource's status doesn't have  loop5-7 device
  disks:
  - name: vdc
    partitions:
      "2":
        last: 10738466815
        name: carina.io/c352dfc41cdd
        number: 2
        start: 5369757696
    path: /dev/vdc
    sectorSize: 512
    size: 11811160064
    udevInfo:
      name: vdc
      properties:
        DEVNAME: /dev/vdc
        DEVPATH: /devices/pci0000:00/0000:00:06.0/virtio3/block/vdc
        DEVTYPE: disk
        MAJOR: "253"
        MINOR: "32"
        SUBSYSTEM: block
      sysPath: /devices/pci0000:00/0000:00:06.0/virtio3/block/vdc
  - name: loop2
    path: /dev/loop2
    sectorSize: 512
    size: 16106127360
    udevInfo:
      name: loop2
      properties:
        DEVNAME: /dev/loop2
        DEVPATH: /devices/virtual/block/loop2
        DEVTYPE: disk
        MAJOR: "7"
        MINOR: "2"
        SUBSYSTEM: block
      sysPath: /devices/virtual/block/loop2
  syncTime: "2022-07-22T09:16:44Z"
  vgGroups:
  - lvCount: 4
    pvCount: 5
    pvName: /dev/loop4
    pvs:
    - pvAttr: a--
      pvFmt: lvm2
      pvFree: 4286578688
      pvName: /dev/vdb
      pvSize: 10733223936
      vgName: carina-vg-ssd
    - pvAttr: a--
      pvFmt: lvm2
      pvFree: 11806965760
      pvName: /dev/vdd
      pvSize: 11806965760
      vgName: carina-vg-ssd
    - pvAttr: a--
      pvFmt: lvm2
      pvFree: 16093544448
      pvName: /dev/loop1
      pvSize: 16101933056
      vgName: carina-vg-ssd
    - pvAttr: a--
      pvFmt: lvm2
      pvFree: 16101933056
      pvName: /dev/loop3
      pvSize: 16101933056
      vgName: carina-vg-ssd
    - pvAttr: a--
      pvFmt: lvm2
      pvFree: 16101933056
      pvName: /dev/loop4
      pvSize: 16101933056
      vgName: carina-vg-ssd
    vgAttr: wz--n-
    vgFree: 64390955008
    vgName: carina-vg-ssd
    vgSize: 70845988864

**Comment by fanhaouu** [comment]
I will take a PR to fix this bug.

**Comment by antmoveh** [comment]
Thank you, Carina. There seems to be some unexpected bugs
