### ISSUE TITLE
add a new parameter to SC allowing pods with carina to migrate if host fails

### ISSUE THREAD

**Issue by ZhangZhenhua** [carina-io/carina#95]
**Is your feature request related to a problem?/Why is this needed**

Currently, the end user is responsible for allowing pods with carina to migrate to other nodes if host fails, by add a specific label. This introduces lots of troubles to end users. For example,

* user need to understand this design then use it.
* Many pods are created by operators, user can't inject label to it.

**Describe the solution you'd like in detail**

There are two ways out.

1#, add this label to every pod in carina webhook.
2#, add new parameter to carina sc and add this label to pod with this kind of sc in carina webhook.

I prefer 2# and we can make this parameter default to true.

**Comment by ZhangZhenhua** [comment]
Ah, it's the pod annotation `carina.stroage.io/allow-pod-migration-if-node-notready`, instead of labels.

**Comment by antmoveh** [comment]
### The second option
If SC has `carina.stroage.io/allow-pod-migration-if-notready`, Add `carina.stroage.io /allow-pod-migration-if-node-notready` to pod  annotation via Webhoook

**Comment by antmoveh** [comment]
Assuming that pvc used by a pod comes from multiple sc, the presence of this parameter in one sc will set the pod annotation
