### ISSUE TITLE
You can cancel the creation of a thin-pool volume

### ISSUE THREAD

**Issue by antmoveh** [carina-io/carina#96]
**Is your feature request related to a problem?/Why is this needed**
Carina storage volume management method is discussed

**Describe the solution you'd like in detail**
In early Carina designs, volumes were planned to be stored in snapshots, hence the design of storage volumes Thin-Pool, where each LV was wrapped by a Thin-pool. In fact, the snapshot function was abandoned in the later development of Carina

**Describe alternatives you've considered**
In the performance test, the performance of the volume wrapped by Thin-pool is lower than that of the pure volume. Do we want to support the removal of Thin-pool? It is important to note that the original volume management method is fully compatible even without Thin-pool

**Additional context**

![thin](https://user-images.githubusercontent.com/26082792/182279240-3563705e-ef7a-494c-9740-24d30427643d.png)

**Comment by fanhaouu** [comment]
I will take a PR to fix this bug.
